// Generated by CoffeeScript 2.6.1
(function() {
  //!/usr/bin/env coffee

  //  web-tix/src/server.coffee

  var DB_RMI_Server, db_schema, local_options, options, pg_options, repl, server;

  ({DB_RMI_Server} = require('web-worm/server'));

  ({db_schema} = require('./db_schema'));

  ({local_options, pg_options} = require('./settings'));

  options = local_options;

  server = new DB_RMI_Server(db_schema, pg_options, options);

  if (module.parent) {
    module.exports = server;
  } else {
    // invoked from command line start REPL
    repl = require('repl');
    repl.start('server> ').context.server = server;
  }

}).call(this);
